extends:  
  - spectral:oas  # Base rules for OpenAPI

rules:
  info-description:
    description: "Every API must have an info.description."
    given: "$.info.description"
    severity: error
    then:
      function: truthy

  x-wso2-basePath:
    description: "`x-wso2-basePath` is required for WSO2 deployment."
    given: "$.['x-wso2-basePath']"
    severity: error
    then:
      function: truthy

  # …add any other WSO2-specific or style rules here…
